# Generated by Django 4.2.1 on 2024-03-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_remove_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='file',
        ),
    ]
