# Generated by Django 4.2.1 on 2024-03-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe_name', models.CharField(max_length=30)),
                ('receipe_image', models.ImageField(upload_to='')),
                ('receipe_desc', models.TextField()),
            ],
        ),
    ]
